# Generated by Django 4.0.5 on 2022-06-17 17:35

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('feedback', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FeedBack',
                'verbose_name_plural': 'FeedBack',
            },
        ),
        migrations.CreateModel(
            name='Adverts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('image_1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Classificados')),
                ('image_2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Classificados')),
                ('image_3', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Classificados')),
                ('city', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('contact_1', models.CharField(max_length=20)),
                ('contact_2', models.CharField(blank=True, max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classificado.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adverts',
                'verbose_name_plural': 'Adverts',
            },
        ),
    ]
