# Generated by Django 4.0.5 on 2022-06-17 17:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classificado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverts',
            name='image_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Classificados'),
        ),
        migrations.AlterField(
            model_name='adverts',
            name='image_3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Classificados'),
        ),
    ]
