# Generated by Django 4.0.5 on 2022-06-17 17:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classificado', '0002_alter_adverts_image_2_alter_adverts_image_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adverts',
            name='image_1',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adverts',
            name='image_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='adverts',
            name='image_3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
