# Generated by Django 4.0.5 on 2022-06-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classificado', '0003_alter_adverts_image_1_alter_adverts_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slugy',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adverts',
            name='date',
            field=models.DateField(),
        ),
    ]
