# Generated by Django 4.0.5 on 2022-06-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classificado', '0004_category_slugy_alter_adverts_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slugy',
        ),
    ]
